sonar.projectKey=anand22022002_Devops_pow
sonar.organization=anand22022002
sonar.projectName=DevOpsDock
sonar.projectVersion=1.0

# Source code location
sonar.sources=app
sonar.exclusions=app/genproto/**,app/static/**,app/templates/**,app/vendor/**

# Go language
sonar.go.coverage.reportPaths=coverage.out
