apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: boutique
spec:
  selector:
    app: cartservice
  ports:
    - name: grpc
      port: 7070
      targetPort: 7070
  type: ClusterIP
