apiVersion: gateway.k8s.aws/v1beta1
kind: LoadBalancerConfiguration
metadata:
  name: kubeinfra-lb-config
  namespace: default
spec:
  scheme: internet-facing
  listenerConfigurations:
    - protocolPort: HTTPS:443
      defaultCertificate: "arn:aws:acm:ap-south-1:222634375010:certificate/ed44e7e1-2dc0-4fe9-a2e6-86922fcd1455"
